teamNameDict = {'ANAHEIM':'ANAHEIM DUCKS',
                'DUCKS':'ANAHEIM DUCKS',
                'ANAHEIM DUCKS':'ANAHEIM DUCKS',
                'ANA':'ANAHEIM DUCKS',
                'ARIZONA':'ARIZONA COYOTES',
                'COYOTES':'ARIZONA COYOTES',
                'ARIZONA COYOTES':'ARIZONA COYOTES',
                'YOTES':'ARIZONA COYOTES',
                'ARI':'ARIZONA COYOTES',
                'BOSTON':'BOSTON BRUINS',
                'BRUINS':'BOSTON BRUINS',
                'BOSTON BRUINS':'BOSTON BRUINS',
                'BOS':'BOSTON BRUINS',
                'BUFFALO':'BUFFALO SABRES',
                'SABRES':'BUFFALO SABRES',
                'BUF':'BUFFALO SABRES',
                'CALGARY':'CALGARY FLAMES',
                'FLAMES':'CALGARY FLAMES',
                'CALGARY FLAMES':'CALGARY FLAMES',
                'CGY':'CALGARY FLAMES',
                'CAROLINA':'CAROLINA HURRICANES',
                'HURRICANES':'CAROLINA HURRICANES',
                'CAROLINA HURRICANES':'CAROLINA HURRICANES',
                'CANES':'CAROLINA HURRICANES',
                'CAR':'CAROLINA HURRICANES',
                'CHICAGO':'CHICAGO BLACKHAWKS',
                'BLACKHAWKS':'CHICAGO BLACKHAWKS',
                'CHICAGO BLACKHAWKS':'CHICAGO BLACKHAWKS',
                'HAWKS':'CHICAGO BLACKHAWKS',
                'CHI':'CHICAGO BLACKHAWKS',
                'COLORADO':'COLORADO AVALANCHE',
                'AVALANCHE':'COLORADO AVALANCHE',
                'COLORADO AVALANCHE':'COLORADO AVALANCHE',
                'AVS':'COLORADO AVALANCHE',
                'COL':'COLORADO AVALANCHE',
                'COLUMBUS':'COLUMBUS BLUE JACKETS',
                'BLUE JACKETS':'COLUMBUS BLUE JACKETS',
                'JACKETS':'COLUMBUS BLUE JACKETS',
                'COLUMBUS BLUE JACKETS':'COLUMBUS BLUE JACKETS',
                'CBJ':'COLUMBUS BLUE JACKETS',
                'DALLAS':'DALLAS STARS',
                'STARS':'DALLAS STARS',
                'DALLAS STARS':'DALLAS STARS',
                'DAL':'DALLAS STARS',
                'DETROIT':'DETROIT RED WINGS',
                'RED WINGS':'DETROIT RED WINGS',
                'WINGS':'DETROIT RED WINGS',
                'DETROIT RED WINGS':'DETROIT RED WINGS',
                'DET':'DETROIT RED WINGS',
                'EDMONTON':'EDMONTON OILERS',
                'OILERS':'EDMONTON OILERS',
                'EDMONTON OILERS':'EDMONTON OILERS',
                'EDM':'EDMONTON OILERS',
                'FLORIDA':'FLORIDA PANTHERS',
                'PANTHERS':'FLORIDA PANTHERS',
                'FLORIDA PANTHERS':'FLORIDA PANTHERS',
                'CATS':'FLORIDA PANTHERS',
                'FLA':'FLORIDA PANTHERS',
                'LOS ANGELES':'LOS ANGELES KINGS',
                'KINGS':'LOS ANGELES KINGS',
                'LOS ANGELES KINGS':'LOS ANGELES KINGS',
                'LA':'LOS ANGELES KINGS',
                'L.A':'LOS ANGELES KINGS',
                'L.A.':'LOS ANGELES KINGS',
                'LAK':'LOS ANGELES KINGS',
                'MINNESOTA':'MINNESOTA WILD',
                'WILD':'MINNESOTA WILD',
                'MINNESOTA WILD':'MINNESOTA WILD',
                'MIN':'MINNESOTA WILD',
                'MONTREAL':'MONTREAL CANADIENS',
                'CANADIENS':'MONTREAL CANADIENS',
                'MONTREAL CANADIENS':'MONTREAL CANADIENS',
                'HABS':'MONTREAL CANADIENS',
                'MTL':'MONTREAL CANADIENS',
                'NASHVILLE':'NASHVILLE PREDATORS',
                'PREDATORS':'NASHVILLE PREDATORS',
                'NASHVILLE PREDATORS':'NASHVILLE PREDATORS',
                'PREDS':'NASHVILLE PREDATORS',
                'NSH':'NASHVILLE PREDATORS',
                'NEW JERSEY':'NEW JERSEY DEVILS',
                'JERSEY':'NEW JERSEY DEVILS',
                'DEVILS':'NEW JERSEY DEVILS',
                'NEW JERSEY DEVILS':'NEW JERSEY DEVILS',
                'NJD':'NEW JERSEY DEVILS',
                'ISLANDERS':'NEW YORK ISLANDERS',
                'NEW YORK ISLANDERS':'NEW YORK ISLANDERS',
                'ISLES':'NEW YORK ISLANDERS',
                'NYI':'NEW YORK ISLANDERS',
                'RANGERS':'NEW YORK RANGERS',
                'NEW YORK RANGERS':'NEW YORK ISLANDERS',
                'NYR':'NEW YORK ISLANDERS',
                'OTTAWA':'OTTAWA SENATORS',
                'SENATORS':'OTTAWA SENATORS',
                'OTTAWA SENATORS':'OTTAWA SENATORS',
                'SENS':'OTTAWA SENATORS',
                'OTT':'OTTAWA SENATORS',
                'PHILADELPHIA':'PHILADELPHIA FLYERS',
                'FLYERS':'PHILADELPHIA FLYERS',
                'PHILADELPHIA FLYERS':'PHILADELPHIA FLYERS',
                'PHILLY':'PHILADELPHIA FLYERS',
                'PHI':'PHILADELPHIA FLYERS',
                'PITTSBURGH':'PITTSBURGH PENGUINS',
                'PENGUINS':'PITTSBURGH PENGUINS',
                'PITTSBURGH PENGUINS':'PITTSBURGH PENGUINS',
                'PENS':'PITTSBURGH PENGUINS',
                'PIT':'PITTSBURGH PENGUINS',
                'SAN JOSE':'SAN JOSE SHARKS',
                'SHARKS':'SAN JOSE SHARKS',
                'SAN JOSE SHARKS':'SAN JOSE SHARKS',
                'SHARKIES':'SAN JOSE SHARKS',
                'SJS':'SAN JOSE SHARKS',
                'ST LOUIS':'ST. LOUIS BLUES',
                'ST. LOUIS':'ST. LOUIS BLUES',
                'BLUES':'ST. LOUIS BLUES',
                'ST LOUIS BLUES':'ST. LOUIS BLUES',
                'ST. LOUIS BLUES':'ST. LOUIS BLUES',
                'STL':'ST. LOUIS BLUES',
                'TAMPA':'TAMPA BAY LIGHTNING',
                'TAMPA BAY':'TAMPA BAY LIGHTNING',
                'LIGHTNING':'TAMPA BAY LIGHTNING',
                'TAMPA BAY LIGHTNING':'TAMPA BAY LIGHTNING',
                'BOLTS':'TAMPA BAY LIGHTNING',
                'TBL':'TAMPA BAY LIGHTNING',
                'TORONTO':'TORONTO MAPLE LEAFS',
                'MAPLE LEAFS':'TORONTO MAPLE LEAFS',
                'LEAFS':'TORONTO MAPLE LEAFS',
                'TORONTO MAPLE LEAFS':'TORONTO MAPLE LEAFS',
                'BUDS':'TORONTO MAPLE LEAFS',
                'TML':'TORONTO MAPLE LEAFS',
                'TOR':'TORONTO MAPLE LEAFS',
                'VANCOUVER':'VANCOUVER CANUCKS',
                'CANUCKS':'VANCOUVER CANUCKS',
                'VANCOUVER CANUCKS':'VANCOUVER CANUCKS',
                'NUCKS':'VANCOUVER CANUCKS',
                'VAN':'VANCOUVER CANUCKS',
                'VEGAS':'VEGAS GOLDEN KNIGHTS',
                'KNIGHTS':'VEGAS GOLDEN KNIGHTS',
                'VEGAS GOLDEN KNIGHTS':'VEGAS GOLDEN KNIGHTS',
                'VGK':'VEGAS GOLDEN KNIGHTS',
                'WASHINGTON':'WASHINGTON CAPITALS',
                'CAPITALS':'WASHINGTON CAPITALS',
                'WASHINGTON CAPITALS':'WASHINGTON CAPITALS',
                'CAPS':'WASHINGTON CAPITALS',
                'WSH':'WASHINGTON CAPITALS',
                'WINNIPEG':'WINNIPEG JETS',
                'JETS':'WINNIPEG JETS',
                'WINNIPEG JETS':'WINNIPEG JETS',
                'WPG':'WINNIPEG JETS'
               }

divDict = {'TAMPA BAY LIGHTNING':'ATLANTIC',
           'BOSTON BRUINS':'ATLANTIC',
           'TORONTO MAPLE LEAFS':'ATLANTIC',
           'FLORIDA PANTHERS':'ATLANTIC',
           'MONTREAL CANADIENS':'ATLANTIC',
           'DETROIT RED WINGS':'ATLANTIC',
           'OTTAWA SENATORS':'ATLANTIC',
           'BUFFALO SABRES':'ATLANTIC',
           'WASHINGTON CAPITALS':'METRO',
           'PITTSBURGH PENGUINS':'METRO',
           'PHILADELPHIA FLYERS':'METRO',
           'COLUMBUS BLUE JACKETS':'METRO',
           'NEW JERSEY DEVILS':'METRO',
           'CAROLINA HURRICANES':'METRO',
           'NEW YORK ISLANDERS':'METRO',
           'NEW YORK RANGERS':'METRO',
           'NASHVILLE PREDATORS':'CENTRAL',
           'WINNIPEG JETS':'CENTRAL',
           'MINNESOTA WILD':'CENTRAL',
           'COLORADO AVALANCHE':'CENTRAL',
           'DALLAS STARS':'CENTRAL',
           'ST. LOUIS BLUES':'CENTRAL',
           'CHICAGO BLACKHAWKS':'CENTRAL',
           'VEGAS GOLDEN KNIGHTS':'PACIFIC',
           'SAN JOSE SHARKS':'PACIFIC',
           'LOS ANGELES KINGS':'PACIFIC',
           'ANAHEIM DUCKS':'PACIFIC',
           'CALGARY FLAMES':'PACIFIC',
           'EDMONTON OILERS':'PACIFIC',
           'VANCOUVER CANUCKS':'PACIFIC',
           'ARIZONA COYOTES':'PACIFIC'
          }
